diff --git a/libavformat/Makefile b/libavformat/Makefile
index 8e8a869..1dee9be 100644
--- a/libavformat/Makefile
+++ b/libavformat/Makefile
@@ -175,6 +175,7 @@ OBJS-$(CONFIG_PCM_U32LE_DEMUXER)         += raw.o
 OBJS-$(CONFIG_PCM_U32LE_MUXER)           += raw.o
 OBJS-$(CONFIG_PCM_U8_DEMUXER)            += raw.o
 OBJS-$(CONFIG_PCM_U8_MUXER)              += raw.o
+OBJS-$(CONFIG_CONCAT_DEMUXER)            += m3u.o pls.o playlist.o concat.o concatgen.o datanode.o
 OBJS-$(CONFIG_PSP_MUXER)                 += movenc.o riff.o isom.o avc.o
 OBJS-$(CONFIG_PVA_DEMUXER)               += pva.o
 OBJS-$(CONFIG_QCP_DEMUXER)               += qcp.o
