/*
 * ALS header file for common data
 * Copyright (c) 2009 Thilo Borgmann <thilo.borgmann _at_ googlemail.com>
 *
 * This file is part of FFmpeg.
 *
 * FFmpeg is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * FFmpeg is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with FFmpeg; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 */

/**
 * @file libavcodec/als_data.h
 * MPEG-4 ALS header file for common data
 * @author Thilo Borgmann <thilo.borgmann _at_ googlemail.com>
 */


#ifndef AVCODEC_ALS_DATA_H
#define AVCODEC_ALS_DATA_H


#include <stdint.h>

/** Rice parameters and corresponding index offsets for decoding the
 *  indices of scaled PARCOR values. The table choosen is set globally
 *  by the encoder and stored in ALSSpecificConfig.
 */
int8_t parcor_rice_table[3][20][2] = {
                        {
                        {-52, 4},
                        {-29, 5},
                        {-31, 4},
                        { 19, 4},
                        {-16, 4},
                        { 12, 3},
                        { -7, 3},
                        {  9, 3},
                        { -5, 3},
                        {  6, 3},
                        { -4, 3},
                        {  3, 3},
                        { -3, 2},
                        {  3, 2},
                        { -2, 2},
                        {  3, 2},
                        { -1, 2},
                        {  2, 2},
                        { -1, 2},
                        {  2, 2}
                        },
                        {
                        {-58, 3},
                        {-42, 4},
                        {-46, 4},
                        { 37, 5},
                        {-36, 4},
                        { 29, 4},
                        {-29, 4},
                        { 25, 4},
                        {-23, 4},
                        { 20, 4},
                        {-17, 4},
                        { 16, 4},
                        {-12, 4},
                        { 12, 3},
                        {-10, 4},
                        {  7, 3},
                        { -4, 4},
                        {  3, 3},
                        { -1, 3},
                        {  1, 3}
                        },
                        {
                        {-59, 3},
                        {-45, 5},
                        {-50, 4},
                        { 38, 4},
                        {-39, 4},
                        { 32, 4},
                        {-30, 4},
                        { 25, 3},
                        {-23, 3},
                        { 20, 3},
                        {-20, 3},
                        { 16, 3},
                        {-13, 3},
                        { 10, 3},
                        { -7, 3},
                        {  3, 3},
                        {  0, 3},
                        { -1, 3},
                        {  2, 3},
                        { -1, 2}
                        }
                        };


/** Scaled PARCOR values used for the first two PARCOR coefficients.
 *  To be indexed by the Rice coded indices.
 *  Generated by: parcor_scaled_values[i] = 32 + ((i * (i+1)) << 7) - (1 << 20)
 */
int32_t parcor_scaled_values[] = {-1048544, -1048288, -1047776, -1047008,
                                  -1045984, -1044704, -1043168, -1041376,
                                  -1039328, -1037024, -1034464, -1031648,
                                  -1028576, -1025248, -1021664, -1017824,
                                  -1013728, -1009376, -1004768,  -999904,
                                   -994784,  -989408,  -983776,  -977888,
                                   -971744,  -965344,  -958688,  -951776,
                                   -944608,  -937184,  -929504,  -921568,
                                   -913376,  -904928,  -896224,  -887264,
                                   -878048,  -868576,  -858848,  -848864,
                                   -838624,  -828128,  -817376,  -806368,
                                   -795104,  -783584,  -771808,  -759776,
                                   -747488,  -734944,  -722144,  -709088,
                                   -695776,  -682208,  -668384,  -654304,
                                   -639968,  -625376,  -610528,  -595424,
                                   -580064,  -564448,  -548576,  -532448,
                                   -516064,  -499424,  -482528,  -465376,
                                   -447968,  -430304,  -412384,  -394208,
                                   -375776,  -357088,  -338144,  -318944,
                                   -299488,  -279776,  -259808,  -239584,
                                   -219104,  -198368,  -177376,  -156128,
                                   -134624,  -112864,   -90848,   -68576,
                                    -46048,   -23264,     -224,    23072,
                                     46624,    70432,    94496,   118816,
                                    143392,   168224,   193312,   218656,
                                    244256,   270112,   296224,   322592,
                                    349216,   376096,   403232,   430624,
                                    458272,   486176,   514336,   542752,
                                    571424,   600352,   629536,   658976,
                                    688672,   718624,   748832,   779296,
                                    810016,   840992,   872224,   903712,
                                    935456,   967456,   999712,  1032224};


#endif /* AVCODEC_ALS_DATA_H */
